# Generated by Django 2.1.1 on 2018-10-18 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grade_class', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='院系')),
                ('no', models.CharField(max_length=2, verbose_name='院系编号')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('no', models.CharField(max_length=50, verbose_name='用户名')),
                ('password', models.CharField(default='00000000', max_length=50, verbose_name='密码')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=2, verbose_name='性别')),
                ('is_leave', models.BooleanField(default=False, verbose_name='已离校')),
                ('start_year', models.DateField(verbose_name='入学日期')),
                ('leave_year', models.DateField(verbose_name='离校日期')),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_class.Clas', verbose_name='所属班级')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Department', verbose_name='所在院系')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_class.Grade', verbose_name='所属年级')),
            ],
        ),
    ]
