# Generated by Django 2.1.1 on 2018-10-18 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='教师部门')),
                ('no', models.CharField(max_length=2, verbose_name='部门编号')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=2, verbose_name='性别')),
                ('no', models.CharField(max_length=50, verbose_name='职工号')),
                ('password', models.CharField(default='00000000', max_length=50, verbose_name='密码')),
                ('is_leave', models.BooleanField(default=False, verbose_name='已离职')),
                ('start_year', models.DateField(verbose_name='入职日期')),
                ('leave_year', models.DateField(blank=True, null=True, verbose_name='离职日期')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Department', verbose_name='部门')),
            ],
        ),
    ]
